# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Pramod Murthy'
tagline:          'Machine Learning, Deep Learning Researcher.'
description:      'Researcher'
url:              https://www.pramodmurthy.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
google_analytics: UA-45894387-2
#author:
  #name:           'Pramod Murthy'
  #url:            https://twitter.com/fongandrewc

paginate:         0
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-jupyter-notebook


# Custom vars
version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/murthy-dev

exclude:          ['*.ipynb']

